# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when creating a new project.
project_id = "its-a-match-talk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[functions.generate]
verify_jwt = true
